# Generated by Django 3.2.6 on 2021-08-09 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210809_1935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
