# Generated by Django 3.2.6 on 2021-08-09 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
