# Generated by Django 3.2.6 on 2021-11-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0003_remove_sentiment_personal_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
