# Generated by Django 3.2.6 on 2021-11-27 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0004_sentiment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentiment',
            name='rating',
        ),
    ]
