# Generated by Django 3.2.6 on 2021-08-12 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0005_alter_message_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date',
            new_name='date_created',
        ),
    ]
