# Generated by Django 3.2.6 on 2021-08-12 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mood', '0006_rename_date_message_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_medication', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ManyToManyField(blank=True, related_name='medication', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
