# Generated by Django 3.2.6 on 2021-08-12 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mood', '0008_alter_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='medication', to=settings.AUTH_USER_MODEL),
        ),
    ]
