# Generated by Django 3.2.6 on 2021-08-20 02:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mood', '0009_alter_medication_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='user',
            field=models.ManyToManyField(null=True, related_name='medication', to=settings.AUTH_USER_MODEL),
        ),
    ]
