# Generated by Django 3.2.6 on 2021-11-21 04:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0012_auto_20211121_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='sentiment',
            field=models.IntegerField(),
        ),
    ]
