# Generated by Django 3.2.6 on 2021-11-21 04:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0013_auto_20211121_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
