# Generated by Django 3.2.6 on 2021-11-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0014_medication_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
