# Generated by Django 3.2.6 on 2021-11-27 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0005_remove_sentiment_rating'),
        ('mood', '0015_auto_20211124_1727'),
    ]

    operations = [
    ]
