# Generated by Django 3.2.6 on 2021-12-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0023_alter_sentiment_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
