# Generated by Django 3.2.6 on 2021-12-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0025_auto_20211205_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
