# Generated by Django 3.2.6 on 2021-12-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0027_alter_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='message',
            field=models.TextField(default='i feel great'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
