# Generated by Django 3.2.6 on 2021-12-19 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0030_deletedmedication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deletedmedication',
            old_name='description',
            new_name='reason',
        ),
    ]
