# Generated by Django 4.0 on 2022-03-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0031_rename_description_deletedmedication_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment',
            name='message',
            field=models.TextField(blank=True, max_length=280, null=True),
        ),
    ]
